### ISSUE TITLE
Fails to build if libgit2 is not installed into standard location (/usr/include)

### ISSUE THREAD

**Issue by dolivier** [libgit2/luagit2#6]
I needed to rebuild luagit, because Ubuntu libgit2 packages are now at v0.19, but luagit is not yet compatible with this version (the changes from v0.17 to v0.19 seemed too important to just hack luagit without more understanding).

So I compiled libgit2 v0.17, but installed it into /usr/local, but I encountered build errors.

My solution was to add the following line:
    set(CFLAGS ${GIT2_CFLAGS})

There might be a better way, and that is the reason I am opening this issue.

**Comment by Neopallium** [comment]
Luagit2 should build against newer libgit2 verions.  I have tested that it compiles against version 1.1.  Also supports newer Lua version (5.1 -> 5.4).
